// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "proto_message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* request_person_info_message_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  request_person_info_message_reflection_ = NULL;
const ::google::protobuf::Descriptor* response_person_info_message_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  response_person_info_message_reflection_ = NULL;
const ::google::protobuf::Descriptor* auto_weather_message_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  auto_weather_message_reflection_ = NULL;
const ::google::protobuf::Descriptor* response_error_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  response_error_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_proto_5fmessage_2eproto() {
  protobuf_AddDesc_proto_5fmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "proto_message.proto");
  GOOGLE_CHECK(file != NULL);
  request_person_info_message_descriptor_ = file->message_type(0);
  static const int request_person_info_message_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_person_info_message, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_person_info_message, age_),
  };
  request_person_info_message_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      request_person_info_message_descriptor_,
      request_person_info_message::default_instance_,
      request_person_info_message_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_person_info_message, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(request_person_info_message, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(request_person_info_message));
  response_person_info_message_descriptor_ = file->message_type(1);
  static const int response_person_info_message_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_person_info_message, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_person_info_message, age_),
  };
  response_person_info_message_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      response_person_info_message_descriptor_,
      response_person_info_message::default_instance_,
      response_person_info_message_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_person_info_message, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_person_info_message, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(response_person_info_message));
  auto_weather_message_descriptor_ = file->message_type(2);
  static const int auto_weather_message_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(auto_weather_message, city_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(auto_weather_message, weather_),
  };
  auto_weather_message_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      auto_weather_message_descriptor_,
      auto_weather_message::default_instance_,
      auto_weather_message_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(auto_weather_message, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(auto_weather_message, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(auto_weather_message));
  response_error_descriptor_ = file->message_type(3);
  static const int response_error_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_error, error_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_error, error_string_),
  };
  response_error_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      response_error_descriptor_,
      response_error::default_instance_,
      response_error_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_error, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(response_error, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(response_error));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_proto_5fmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    request_person_info_message_descriptor_, &request_person_info_message::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    response_person_info_message_descriptor_, &response_person_info_message::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    auto_weather_message_descriptor_, &auto_weather_message::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    response_error_descriptor_, &response_error::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_proto_5fmessage_2eproto() {
  delete request_person_info_message::default_instance_;
  delete request_person_info_message_reflection_;
  delete response_person_info_message::default_instance_;
  delete response_person_info_message_reflection_;
  delete auto_weather_message::default_instance_;
  delete auto_weather_message_reflection_;
  delete response_error::default_instance_;
  delete response_error_reflection_;
}

void protobuf_AddDesc_proto_5fmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023proto_message.proto\"8\n\033request_person_"
    "info_message\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\""
    "9\n\034response_person_info_message\022\014\n\004name\030"
    "\001 \001(\t\022\013\n\003age\030\002 \001(\005\":\n\024auto_weather_messa"
    "ge\022\021\n\tcity_name\030\001 \001(\t\022\017\n\007weather\030\002 \001(\t\":"
    "\n\016response_error\022\022\n\nerror_code\030\001 \001(\005\022\024\n\014"
    "error_string\030\002 \001(\t", 258);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto_message.proto", &protobuf_RegisterTypes);
  request_person_info_message::default_instance_ = new request_person_info_message();
  response_person_info_message::default_instance_ = new response_person_info_message();
  auto_weather_message::default_instance_ = new auto_weather_message();
  response_error::default_instance_ = new response_error();
  request_person_info_message::default_instance_->InitAsDefaultInstance();
  response_person_info_message::default_instance_->InitAsDefaultInstance();
  auto_weather_message::default_instance_->InitAsDefaultInstance();
  response_error::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_proto_5fmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_proto_5fmessage_2eproto {
  StaticDescriptorInitializer_proto_5fmessage_2eproto() {
    protobuf_AddDesc_proto_5fmessage_2eproto();
  }
} static_descriptor_initializer_proto_5fmessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int request_person_info_message::kNameFieldNumber;
const int request_person_info_message::kAgeFieldNumber;
#endif  // !_MSC_VER

request_person_info_message::request_person_info_message()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void request_person_info_message::InitAsDefaultInstance() {
}

request_person_info_message::request_person_info_message(const request_person_info_message& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void request_person_info_message::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  age_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

request_person_info_message::~request_person_info_message() {
  SharedDtor();
}

void request_person_info_message::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void request_person_info_message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* request_person_info_message::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return request_person_info_message_descriptor_;
}

const request_person_info_message& request_person_info_message::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_5fmessage_2eproto();
  return *default_instance_;
}

request_person_info_message* request_person_info_message::default_instance_ = NULL;

request_person_info_message* request_person_info_message::New() const {
  return new request_person_info_message;
}

void request_person_info_message::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    age_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool request_person_info_message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_age;
        break;
      }

      // optional int32 age = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_age:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &age_)));
          set_has_age();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void request_person_info_message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // optional int32 age = 2;
  if (has_age()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->age(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* request_person_info_message::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional int32 age = 2;
  if (has_age()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->age(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int request_person_info_message::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional int32 age = 2;
    if (has_age()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->age());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void request_person_info_message::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const request_person_info_message* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const request_person_info_message*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void request_person_info_message::MergeFrom(const request_person_info_message& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_age()) {
      set_age(from.age());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void request_person_info_message::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void request_person_info_message::CopyFrom(const request_person_info_message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool request_person_info_message::IsInitialized() const {

  return true;
}

void request_person_info_message::Swap(request_person_info_message* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(age_, other->age_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata request_person_info_message::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = request_person_info_message_descriptor_;
  metadata.reflection = request_person_info_message_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int response_person_info_message::kNameFieldNumber;
const int response_person_info_message::kAgeFieldNumber;
#endif  // !_MSC_VER

response_person_info_message::response_person_info_message()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void response_person_info_message::InitAsDefaultInstance() {
}

response_person_info_message::response_person_info_message(const response_person_info_message& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void response_person_info_message::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  age_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

response_person_info_message::~response_person_info_message() {
  SharedDtor();
}

void response_person_info_message::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void response_person_info_message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* response_person_info_message::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return response_person_info_message_descriptor_;
}

const response_person_info_message& response_person_info_message::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_5fmessage_2eproto();
  return *default_instance_;
}

response_person_info_message* response_person_info_message::default_instance_ = NULL;

response_person_info_message* response_person_info_message::New() const {
  return new response_person_info_message;
}

void response_person_info_message::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    age_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool response_person_info_message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_age;
        break;
      }

      // optional int32 age = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_age:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &age_)));
          set_has_age();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void response_person_info_message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // optional int32 age = 2;
  if (has_age()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->age(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* response_person_info_message::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional int32 age = 2;
  if (has_age()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->age(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int response_person_info_message::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional int32 age = 2;
    if (has_age()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->age());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void response_person_info_message::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const response_person_info_message* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const response_person_info_message*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void response_person_info_message::MergeFrom(const response_person_info_message& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_age()) {
      set_age(from.age());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void response_person_info_message::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void response_person_info_message::CopyFrom(const response_person_info_message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool response_person_info_message::IsInitialized() const {

  return true;
}

void response_person_info_message::Swap(response_person_info_message* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(age_, other->age_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata response_person_info_message::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = response_person_info_message_descriptor_;
  metadata.reflection = response_person_info_message_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int auto_weather_message::kCityNameFieldNumber;
const int auto_weather_message::kWeatherFieldNumber;
#endif  // !_MSC_VER

auto_weather_message::auto_weather_message()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void auto_weather_message::InitAsDefaultInstance() {
}

auto_weather_message::auto_weather_message(const auto_weather_message& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void auto_weather_message::SharedCtor() {
  _cached_size_ = 0;
  city_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  weather_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

auto_weather_message::~auto_weather_message() {
  SharedDtor();
}

void auto_weather_message::SharedDtor() {
  if (city_name_ != &::google::protobuf::internal::kEmptyString) {
    delete city_name_;
  }
  if (weather_ != &::google::protobuf::internal::kEmptyString) {
    delete weather_;
  }
  if (this != default_instance_) {
  }
}

void auto_weather_message::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* auto_weather_message::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return auto_weather_message_descriptor_;
}

const auto_weather_message& auto_weather_message::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_5fmessage_2eproto();
  return *default_instance_;
}

auto_weather_message* auto_weather_message::default_instance_ = NULL;

auto_weather_message* auto_weather_message::New() const {
  return new auto_weather_message;
}

void auto_weather_message::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_city_name()) {
      if (city_name_ != &::google::protobuf::internal::kEmptyString) {
        city_name_->clear();
      }
    }
    if (has_weather()) {
      if (weather_ != &::google::protobuf::internal::kEmptyString) {
        weather_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool auto_weather_message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string city_name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_city_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->city_name().data(), this->city_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_weather;
        break;
      }

      // optional string weather = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_weather:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_weather()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->weather().data(), this->weather().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void auto_weather_message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string city_name = 1;
  if (has_city_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->city_name().data(), this->city_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->city_name(), output);
  }

  // optional string weather = 2;
  if (has_weather()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->weather().data(), this->weather().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->weather(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* auto_weather_message::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string city_name = 1;
  if (has_city_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->city_name().data(), this->city_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->city_name(), target);
  }

  // optional string weather = 2;
  if (has_weather()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->weather().data(), this->weather().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->weather(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int auto_weather_message::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string city_name = 1;
    if (has_city_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->city_name());
    }

    // optional string weather = 2;
    if (has_weather()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->weather());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void auto_weather_message::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const auto_weather_message* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const auto_weather_message*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void auto_weather_message::MergeFrom(const auto_weather_message& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_city_name()) {
      set_city_name(from.city_name());
    }
    if (from.has_weather()) {
      set_weather(from.weather());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void auto_weather_message::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void auto_weather_message::CopyFrom(const auto_weather_message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool auto_weather_message::IsInitialized() const {

  return true;
}

void auto_weather_message::Swap(auto_weather_message* other) {
  if (other != this) {
    std::swap(city_name_, other->city_name_);
    std::swap(weather_, other->weather_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata auto_weather_message::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = auto_weather_message_descriptor_;
  metadata.reflection = auto_weather_message_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int response_error::kErrorCodeFieldNumber;
const int response_error::kErrorStringFieldNumber;
#endif  // !_MSC_VER

response_error::response_error()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void response_error::InitAsDefaultInstance() {
}

response_error::response_error(const response_error& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void response_error::SharedCtor() {
  _cached_size_ = 0;
  error_code_ = 0;
  error_string_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

response_error::~response_error() {
  SharedDtor();
}

void response_error::SharedDtor() {
  if (error_string_ != &::google::protobuf::internal::kEmptyString) {
    delete error_string_;
  }
  if (this != default_instance_) {
  }
}

void response_error::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* response_error::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return response_error_descriptor_;
}

const response_error& response_error::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_proto_5fmessage_2eproto();
  return *default_instance_;
}

response_error* response_error::default_instance_ = NULL;

response_error* response_error::New() const {
  return new response_error;
}

void response_error::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    error_code_ = 0;
    if (has_error_string()) {
      if (error_string_ != &::google::protobuf::internal::kEmptyString) {
        error_string_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool response_error::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 error_code = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_code_)));
          set_has_error_code();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_error_string;
        break;
      }

      // optional string error_string = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_error_string:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_error_string()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->error_string().data(), this->error_string().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void response_error::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 error_code = 1;
  if (has_error_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error_code(), output);
  }

  // optional string error_string = 2;
  if (has_error_string()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->error_string().data(), this->error_string().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->error_string(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* response_error::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 error_code = 1;
  if (has_error_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->error_code(), target);
  }

  // optional string error_string = 2;
  if (has_error_string()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->error_string().data(), this->error_string().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->error_string(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int response_error::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 error_code = 1;
    if (has_error_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->error_code());
    }

    // optional string error_string = 2;
    if (has_error_string()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->error_string());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void response_error::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const response_error* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const response_error*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void response_error::MergeFrom(const response_error& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_error_code()) {
      set_error_code(from.error_code());
    }
    if (from.has_error_string()) {
      set_error_string(from.error_string());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void response_error::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void response_error::CopyFrom(const response_error& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool response_error::IsInitialized() const {

  return true;
}

void response_error::Swap(response_error* other) {
  if (other != this) {
    std::swap(error_code_, other->error_code_);
    std::swap(error_string_, other->error_string_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata response_error::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = response_error_descriptor_;
  metadata.reflection = response_error_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
