// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class echo_message;
class news;

// ===================================================================

class echo_message : public ::google::protobuf::Message {
 public:
  echo_message();
  virtual ~echo_message();

  echo_message(const echo_message& from);

  inline echo_message& operator=(const echo_message& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const echo_message& default_instance();

  void Swap(echo_message* other);

  // implements Message ----------------------------------------------

  echo_message* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const echo_message& from);
  void MergeFrom(const echo_message& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string echo_str = 1;
  inline bool has_echo_str() const;
  inline void clear_echo_str();
  static const int kEchoStrFieldNumber = 1;
  inline const ::std::string& echo_str() const;
  inline void set_echo_str(const ::std::string& value);
  inline void set_echo_str(const char* value);
  inline void set_echo_str(const char* value, size_t size);
  inline ::std::string* mutable_echo_str();
  inline ::std::string* release_echo_str();
  inline void set_allocated_echo_str(::std::string* echo_str);

  // optional int32 echo_num = 2;
  inline bool has_echo_num() const;
  inline void clear_echo_num();
  static const int kEchoNumFieldNumber = 2;
  inline ::google::protobuf::int32 echo_num() const;
  inline void set_echo_num(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:echo_message)
 private:
  inline void set_has_echo_str();
  inline void clear_has_echo_str();
  inline void set_has_echo_num();
  inline void clear_has_echo_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* echo_str_;
  ::google::protobuf::int32 echo_num_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static echo_message* default_instance_;
};
// -------------------------------------------------------------------

class news : public ::google::protobuf::Message {
 public:
  news();
  virtual ~news();

  news(const news& from);

  inline news& operator=(const news& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const news& default_instance();

  void Swap(news* other);

  // implements Message ----------------------------------------------

  news* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const news& from);
  void MergeFrom(const news& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string str = 1;
  inline bool has_str() const;
  inline void clear_str();
  static const int kStrFieldNumber = 1;
  inline const ::std::string& str() const;
  inline void set_str(const ::std::string& value);
  inline void set_str(const char* value);
  inline void set_str(const char* value, size_t size);
  inline ::std::string* mutable_str();
  inline ::std::string* release_str();
  inline void set_allocated_str(::std::string* str);

  // @@protoc_insertion_point(class_scope:news)
 private:
  inline void set_has_str();
  inline void clear_has_str();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* str_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static news* default_instance_;
};
// ===================================================================


// ===================================================================

// echo_message

// optional string echo_str = 1;
inline bool echo_message::has_echo_str() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void echo_message::set_has_echo_str() {
  _has_bits_[0] |= 0x00000001u;
}
inline void echo_message::clear_has_echo_str() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void echo_message::clear_echo_str() {
  if (echo_str_ != &::google::protobuf::internal::kEmptyString) {
    echo_str_->clear();
  }
  clear_has_echo_str();
}
inline const ::std::string& echo_message::echo_str() const {
  return *echo_str_;
}
inline void echo_message::set_echo_str(const ::std::string& value) {
  set_has_echo_str();
  if (echo_str_ == &::google::protobuf::internal::kEmptyString) {
    echo_str_ = new ::std::string;
  }
  echo_str_->assign(value);
}
inline void echo_message::set_echo_str(const char* value) {
  set_has_echo_str();
  if (echo_str_ == &::google::protobuf::internal::kEmptyString) {
    echo_str_ = new ::std::string;
  }
  echo_str_->assign(value);
}
inline void echo_message::set_echo_str(const char* value, size_t size) {
  set_has_echo_str();
  if (echo_str_ == &::google::protobuf::internal::kEmptyString) {
    echo_str_ = new ::std::string;
  }
  echo_str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* echo_message::mutable_echo_str() {
  set_has_echo_str();
  if (echo_str_ == &::google::protobuf::internal::kEmptyString) {
    echo_str_ = new ::std::string;
  }
  return echo_str_;
}
inline ::std::string* echo_message::release_echo_str() {
  clear_has_echo_str();
  if (echo_str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = echo_str_;
    echo_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void echo_message::set_allocated_echo_str(::std::string* echo_str) {
  if (echo_str_ != &::google::protobuf::internal::kEmptyString) {
    delete echo_str_;
  }
  if (echo_str) {
    set_has_echo_str();
    echo_str_ = echo_str;
  } else {
    clear_has_echo_str();
    echo_str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 echo_num = 2;
inline bool echo_message::has_echo_num() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void echo_message::set_has_echo_num() {
  _has_bits_[0] |= 0x00000002u;
}
inline void echo_message::clear_has_echo_num() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void echo_message::clear_echo_num() {
  echo_num_ = 0;
  clear_has_echo_num();
}
inline ::google::protobuf::int32 echo_message::echo_num() const {
  return echo_num_;
}
inline void echo_message::set_echo_num(::google::protobuf::int32 value) {
  set_has_echo_num();
  echo_num_ = value;
}

// -------------------------------------------------------------------

// news

// optional string str = 1;
inline bool news::has_str() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void news::set_has_str() {
  _has_bits_[0] |= 0x00000001u;
}
inline void news::clear_has_str() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void news::clear_str() {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    str_->clear();
  }
  clear_has_str();
}
inline const ::std::string& news::str() const {
  return *str_;
}
inline void news::set_str(const ::std::string& value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void news::set_str(const char* value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void news::set_str(const char* value, size_t size) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* news::mutable_str() {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  return str_;
}
inline ::std::string* news::release_str() {
  clear_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = str_;
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void news::set_allocated_str(::std::string* str) {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    delete str_;
  }
  if (str) {
    set_has_str();
    str_ = str;
  } else {
    clear_has_str();
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
